App:
  env: local
  port: 8888
  app_name: gin_app
  app_url: http://localhost

Log:
  Level: info
  root_dir: ./storage/logs
  filename: app.log
  format: json
  show_line: true
  max_backups: 10
  max_size: 200
  max_age: 30
  compress: true

database:
  driver: mysql # database driver
  host: 127.0.0.1
  port: 8306
  database: go-test
  username: root
  password: root
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: info # log level
  enable_file_log_writer: true
  log_filename: sql.log
